# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oxlos', '0002_auto_20170415_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='instructions',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='instructions_html',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
