# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oxlos', '0003_auto_20170415_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='description_html',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='task',
            name='question_template',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
